### ISSUE TITLE
Add timezone variable in terraform.tfvars.example

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-base#2]
In terraform.tfvars, I had to add a **timezone** variable for terraform apply to work. I wasn’t sure what string format the time zone should be in. So I tried the IANA time zone format, “America/Los_Angeles”, and it worked. Please add this variable to terraform.tfvars.example, with a comment about the time zone format.

**Comment by hyder** [comment]
merged in #5 

thanks for your contribution
