### ISSUE TITLE
Make the notification & subscription resources dependent on the bastion instance

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-base#26]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

`oci_ons_notification_topic`
`oci_ons_subscription`

### Terraform Configuration Files

`modules/bastion/ons.tf`

### Expected Behavior

When `bastion_enabled = false`, the notification topic and the subscription for the bastion must not be created.

### Actual Behavior

The notification topic and the subscription for the bastion are created even if `bastion_enabled = false`

**Comment by hyder** [comment]
fixed in #28
