### ISSUE TITLE
Remove ssh_private_key_path variable

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-base#3]
@hyder , in our offline email exchange, you clarified that the ssh_private_key_path variable is not needed for the bastion module, and asked me to file an issue to remove it.

**Comment by hyder** [comment]
We'll keep this for now, until we can evaluate downstream impact on other projects such https://github.com/oracle-terraform-modules/terraform-oci-oke

Let's revisit this later.
