### ISSUE TITLE
Use compartment_id to create the instance principal policy

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-base#4]
@hyder , per our email conversation...

To create the policy we could use the compartment_id instead of compartment_name:

`Allow dynamic-group base-bastion-instance-principal to manage all-resources in compartment id <ocid>`

If we take this route, then we can remove compartment_name from the list of input variables. Please consider this suggestion.

**Comment by hyder** [comment]
merged in #5
