### ISSUE TITLE
Why not use the `netnum` argument name for `subnets`?

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-base#8]
To determine the values for the `newbits` and `subnets` variables, users would have to learn about the `cidrsubnet` function, by reading https://www.terraform.io/docs/configuration/functions/cidrsubnet.html). To make that learning experience just a tad bit easier, consider changing the name of the `subnets` variable to `netnum`, i.e., consistent with the arguments names of the `cidrsubnet` function.

**Comment by hyder** [comment]
I thought by naming it subnets, it would be easier for users to understand but I see your point.

Can you submit a PR when you can?

**Comment by hyder** [comment]
fixed in #10
