### ISSUE TITLE
By default module is bastion enabled and operator enabled but documentation says its optional , so default has to be disabled in codebase

### ISSUE THREAD

**Issue by SaurabhAhuja-Dev** [oracle-terraform-modules/terraform-oci-base#82]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version and Provider Version

terraform --version                                                                                                                                                              
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/oci v4.14.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

oci_core_instance
bastion

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. 
# Please remove any sensitive information from configuration files before sharing them. 
```

### Expected Behavior

By filling mandatory parameters, terraform plan should pass.

### Actual Behavior
terraform plan fails for bastion resources creation as it is set as default enabled etc. Either documentation should says its mandatory or it should be default false in codebase

### Steps to Reproduce

1. `terraform apply`
a) Fill mandatory parameters
b) terraform init
Terraform has been successfully initialized!
c) terraform plan                                                                                                                                                                   

Error: Invalid function argument

  on .terraform/modules/bastion/compute.tf line 29, in resource "oci_core_instance" "bastion":
  29:     ssh_authorized_keys = var.ssh_public_key != "" ? var.ssh_public_key : file(var.ssh_public_key_path)
    |----------------
    | var.ssh_public_key_path is ""

Invalid value for "path" parameter: failed to read ..

Error: Invalid function argument

  on .terraform/modules/operator/compute.tf line 35, in resource "oci_core_instance" "operator":
  35:     ssh_authorized_keys = var.ssh_public_key != "" ? var.ssh_public_key : file(var.ssh_public_key_path)
    |----------------
    | var.ssh_public_key_path is ""

Invalid value for "path" parameter: failed to read ..

**Comment by SaurabhAhuja-Dev** [comment]
I can probably make it default false, let me know if i can open PR and fix this?

**Comment by hyder** [comment]
The default  for whether the bastion is already enabled is false: https://github.com/oracle-terraform-modules/terraform-oci-base/blob/master/variables.tf#L77.

The error you're getting is that you have the bastion enabled but you failed to provide the public ssh key - either the key itself or the path to the key.

**Comment by SaurabhAhuja-Dev** [comment]
I ran "cp terraform.tfvars.example terraform.tfvars" as documented.
guess, issue is coming from this example file which sets default as enabled https://github.com/oracle-terraform-modules/terraform-oci-base/blob/master/terraform.tfvars.example

**Comment by hyder** [comment]
Right. So, before you log bugs against the codebase, it would help if 

1. you can show your troubleshooting steps, expected and actual behaviour
2. you can pinpoint the area where you think the bug is
3. you can show how to replicate this behaviour

All 3 above are in the issue - bug template. 

If the issue is as minor as a default value in an example configuration file, you can just submit a PR with explanation in your PR.

**Comment by SaurabhAhuja-Dev** [comment]
yea sure, i missed it, next time i will add them
