### ISSUE TITLE
Provider not defined for non-home region?

### ISSUE THREAD

**Issue by kumar-dhanagopal** [oracle-terraform-modules/terraform-oci-base#9]
@hyder - Hi Ali, when I tested the terraform-oci-base config the other day, I had set region to us-ashburn-1 and everything worked. But when I tested with region=us-phoenix-1 today, the resources were still created in Ashburn (the home region)!  I suspect that only one provider is defined, i.e., for the home region.  Am I missing anything?

**Comment by hyder** [comment]
As we want the base module to be reusable, we haven't created the provider. This is expected to be define in the root of the project that is using the base module.

However, if you're testing the base module on its own, you need to explicitly create your provider. See here: https://github.com/oracle-terraform-modules/terraform-oci-base/blob/master/docs/quickstart.adoc#instructions (Step 5)

**Comment by kumar-dhanagopal** [comment]
I missed reading that part. Thank you!
